void history_day1() {
  Firebase.setString("History/d30",Firebase.getString("History/d29"));
  Firebase.setString("History/d29",Firebase.getString("History/d28"));
  Firebase.setString("History/d28",Firebase.getString("History/d27"));
  Firebase.setString("History/d27",Firebase.getString("History/d26"));
  Firebase.setString("History/d26",Firebase.getString("History/d25"));
  Firebase.setString("History/d25",Firebase.getString("History/d24"));
  Firebase.setString("History/d24",Firebase.getString("History/d23"));
  Firebase.setString("History/d23",Firebase.getString("History/d22"));
  Firebase.setString("History/d22",Firebase.getString("History/d21"));
  Firebase.setString("History/d21",Firebase.getString("History/d20"));
  Firebase.setString("History/d20",Firebase.getString("History/d19"));
  Firebase.setString("History/d19",Firebase.getString("History/d18"));
  Firebase.setString("History/d18",Firebase.getString("History/d17"));
  Firebase.setString("History/d17",Firebase.getString("History/d16"));
  Firebase.setString("History/d16",Firebase.getString("History/d15"));
  Firebase.setString("History/d15",Firebase.getString("History/d14"));
  Firebase.setString("History/d14",Firebase.getString("History/d13"));
  Firebase.setString("History/d13",Firebase.getString("History/d12"));
  Firebase.setString("History/d12",Firebase.getString("History/d11"));
  Firebase.setString("History/d11",Firebase.getString("History/d10"));
  Firebase.setString("History/d10",Firebase.getString("History/d9"));
  Firebase.setString("History/d9",Firebase.getString("History/d8"));
  Firebase.setString("History/d8",Firebase.getString("History/d7"));
  Firebase.setString("History/d7",Firebase.getString("History/d6"));
  Firebase.setString("History/d6",Firebase.getString("History/d5"));
  Firebase.setString("History/d5",Firebase.getString("History/d4"));
  Firebase.setString("History/d4",Firebase.getString("History/d3"));
  Firebase.setString("History/d3",Firebase.getString("History/d2"));
  Firebase.setString("History/d2",Firebase.getString("History/d1"));
  Firebase.setString("History/d1", history_day);
}

void history_hf(){   
  Firebase.setString("History/hf30",Firebase.getString("History/hf29"));
  Firebase.setString("History/hf29",Firebase.getString("History/hf28"));
  Firebase.setString("History/hf28",Firebase.getString("History/hf27"));
  Firebase.setString("History/hf27",Firebase.getString("History/hf26"));
  Firebase.setString("History/hf26",Firebase.getString("History/hf25"));
  Firebase.setString("History/hf25",Firebase.getString("History/hf24"));
  Firebase.setString("History/hf24",Firebase.getString("History/hf23"));
  Firebase.setString("History/hf23",Firebase.getString("History/hf22"));
  Firebase.setString("History/hf22",Firebase.getString("History/hf21"));
  Firebase.setString("History/hf21",Firebase.getString("History/hf20"));
  Firebase.setString("History/hf20",Firebase.getString("History/hf19"));
  Firebase.setString("History/hf19",Firebase.getString("History/hf18"));
  Firebase.setString("History/hf18",Firebase.getString("History/hf17"));
  Firebase.setString("History/hf17",Firebase.getString("History/hf16"));
  Firebase.setString("History/hf16",Firebase.getString("History/hf15"));
  Firebase.setString("History/hf15",Firebase.getString("History/hf14"));
  Firebase.setString("History/hf14",Firebase.getString("History/hf13"));
  Firebase.setString("History/hf13",Firebase.getString("History/hf12"));
  Firebase.setString("History/hf12",Firebase.getString("History/hf11"));
  Firebase.setString("History/hf11",Firebase.getString("History/hf10"));
  Firebase.setString("History/hf10",Firebase.getString("History/hf9"));
  Firebase.setString("History/hf9",Firebase.getString("History/hf8"));
  Firebase.setString("History/hf8",Firebase.getString("History/hf7"));
  Firebase.setString("History/hf7",Firebase.getString("History/hf6"));
  Firebase.setString("History/hf6",Firebase.getString("History/hf5"));
  Firebase.setString("History/hf5",Firebase.getString("History/hf4"));
  Firebase.setString("History/hf4",Firebase.getString("History/hf3"));
  Firebase.setString("History/hf3",Firebase.getString("History/hf2"));
  Firebase.setString("History/hf2",Firebase.getString("History/hf1"));
  Firebase.setString("History/hf1",t_h_his); 
  
}


void history_ts(){  
  Firebase.setString("History/ts30",Firebase.getString("History/ts29"));
  Firebase.setString("History/ts29",Firebase.getString("History/ts28"));
  Firebase.setString("History/ts28",Firebase.getString("History/ts27"));
  Firebase.setString("History/ts27",Firebase.getString("History/ts26"));
  Firebase.setString("History/ts26",Firebase.getString("History/ts25"));
  Firebase.setString("History/ts25",Firebase.getString("History/ts24"));
  Firebase.setString("History/ts24",Firebase.getString("History/ts23"));
  Firebase.setString("History/ts23",Firebase.getString("History/ts22"));
  Firebase.setString("History/ts22",Firebase.getString("History/ts21"));
  Firebase.setString("History/ts21",Firebase.getString("History/ts20"));
  Firebase.setString("History/ts20",Firebase.getString("History/ts19"));
  Firebase.setString("History/ts19",Firebase.getString("History/ts18"));
  Firebase.setString("History/ts18",Firebase.getString("History/ts17"));
  Firebase.setString("History/ts17",Firebase.getString("History/ts16"));
  Firebase.setString("History/ts16",Firebase.getString("History/ts15"));
  Firebase.setString("History/ts15",Firebase.getString("History/ts14"));
  Firebase.setString("History/ts14",Firebase.getString("History/ts13"));
  Firebase.setString("History/ts13",Firebase.getString("History/ts12"));
  Firebase.setString("History/ts12",Firebase.getString("History/ts11"));
  Firebase.setString("History/ts11",Firebase.getString("History/ts10"));
  Firebase.setString("History/ts10",Firebase.getString("History/ts9"));
  Firebase.setString("History/ts9",Firebase.getString("History/ts8"));
  Firebase.setString("History/ts8",Firebase.getString("History/ts7"));
  Firebase.setString("History/ts7",Firebase.getString("History/ts6"));
  Firebase.setString("History/ts6",Firebase.getString("History/ts5"));
  Firebase.setString("History/ts5",Firebase.getString("History/ts4"));
  Firebase.setString("History/ts4",Firebase.getString("History/ts3"));
  Firebase.setString("History/ts3",Firebase.getString("History/ts2"));
  Firebase.setString("History/ts2",Firebase.getString("History/ts1"));
  Firebase.setString("History/ts1",t_h_his); 
}

